apiVersion: networking.gke.io/v1
kind: MultiClusterService
metadata:
  name: player-sql-mcs
  namespace: player-sql
spec:
  template:
    spec:
      selector:
        app: player-sql
      ports:
      - name: player-sql
        protocol: TCP
        port: 8080
        targetPort: 8080
